//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clabbers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clabbers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap A {
            get {
                object obj = ResourceManager.GetObject("A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15,15
        ///WXXlXXXWXXXlXXW
        ///XwXXXLXXXLXXXwX
        ///XXwXXXlXlXXXwXX
        ///lXXwXXXlXXXwXXl
        ///XXXXwXXXXXwXXXX
        ///XLXXXLXXXLXXXLX
        ///XXlXXXlXlXXXlXX
        ///WXXlXXX*XXXlXXW
        ///XXlXXXlXlXXXlXX
        ///XLXXXLXXXLXXXLX
        ///XXXXwXXXXXwXXXX
        ///lXXwXXXlXXXwXXl
        ///XXwXXXlXlXXXwXX
        ///XwXXXLXXXLXXXwX
        ///WXXlXXXWXXXlXXW.
        /// </summary>
        internal static string DefaultMap {
            get {
                return ResourceManager.GetString("DefaultMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *=2
        ///E=12,A=9,I=9,O=8,N=6,R=6,T=6,L=4,S=4,U=4
        ///D=4,G=3
        ///B=2,C=2,M=2,P=2
        ///F=2,H=2,V=2,W=2,Y=2
        ///K=1
        ///
        ///
        ///J=1,X=1
        ///Q=1,Z=1.
        /// </summary>
        internal static string DefaultTiles {
            get {
                return ResourceManager.GetString("DefaultTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA
        ///AAH
        ///AAHED
        ///AAHING
        ///AAHS
        ///AAL
        ///AALII
        ///AALIIS
        ///AALS
        ///AARDVARK
        ///AARDVARKS
        ///AARDWOLF
        ///AARDWOLVES
        ///AARGH
        ///AARRGH
        ///AARRGHH
        ///AAS
        ///AASVOGEL
        ///AASVOGELS
        ///AB
        ///ABA
        ///ABACA
        ///ABACAS
        ///ABACI
        ///ABACK
        ///ABACTERIAL
        ///ABACUS
        ///ABACUSES
        ///ABAFT
        ///ABAKA
        ///ABAKAS
        ///ABALONE
        ///ABALONES
        ///ABAMP
        ///ABAMPERE
        ///ABAMPERES
        ///ABAMPS
        ///ABANDON
        ///ABANDONED
        ///ABANDONER
        ///ABANDONERS
        ///ABANDONING
        ///ABANDONMENT
        ///ABANDONMENTS
        ///ABANDONS
        ///ABAPICAL
        ///ABAS
        ///ABASE
        ///ABASED
        ///ABASEDLY
        ///ABASEMENT
        ///ABASEMENTS
        ///ABASER
        ///ABASERS
        ///ABASES
        ///ABASH
        ///ABASHED
        ///ABASHEDLY
        ///ABASHES
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultWords {
            get {
                return ResourceManager.GetString("DefaultWords", resourceCulture);
            }
        }
    }
}
