//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEW3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MEW3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /=====\     /=====\
        ///|E....&apos;=====&apos;.....|
        ///|.&lt;=&gt;.........&lt;=&gt;.|
        ///|.....,==2==,.....|
        ///\=,.,=/     \=,.,=/
        ///  |.|         |.|
        ///  |.1         1.|
        ///  |.|         |.|
        ////=&apos;.&apos;=\     /=&apos;.&apos;=\
        ///|.....|     |.....|
        ///|.,=,.&apos;==2==&apos;.,=,.|
        ///|.&apos;=&apos;.........&apos;=&apos;.|
        ///|.....,=====,....!|
        ///\=====/     \=====/.
        /// </summary>
        internal static string BasesMap {
            get {
                return ResourceManager.GetString("BasesMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /===============\ 
        /// |o......|......o| 
        /// |./\./\.|./\./\.| 
        /// |.||.\/.|.\/.||.| 
        /// |.\/.........\/.| 
        /// |..../==.==\....| 
        /// \=.|.|.....|.|.=/ 
        ///1...|.|.| |.|.|...1
        /// /=.|...|!|...|.=\ 
        /// |....|.\=/.|....| 
        /// |.=\.|..E..|./=.| 
        /// |..|.../=\...|..| 
        /// |=.|.|.\=/.|.|.=| 
        /// |....|..|..|....| 
        /// |.=====.|.=====.| 
        /// |o.............o| 
        /// \===============/ .
        /// </summary>
        internal static string DefaultIntentMap {
            get {
                return ResourceManager.GetString("DefaultIntentMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /===============\
        ///|o......|......o|
        ///|./\./\.|./\./\.|
        ///|.||.\/.|.\/.||.|
        ///|.\/.........\/.|
        ///|..../==.==\....|
        ///\=.|.|.....|.|.=/
        ///1..|.|.| |.|.|..1
        ////=.|...|!|...|.=\
        ///|....|.\=/.|....|
        ///|.=\.|..E..|./=.|
        ///|..|.../=\...|..|
        ///|=.|.|.\=/.|.|.=|
        ///|....|..|..|....|
        ///|.=====.|.=====.|
        ///|o.............o|
        ///\===============/.
        /// </summary>
        internal static string DefaultMap {
            get {
                return ResourceManager.GetString("DefaultMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /======\2/======\
        ///|4.............3|
        ///|./\./\.|./\./\.|
        ///|.||.\/.|.\/.||.|
        ///|.\/.........\/.|
        ///|o.../==.==\...o|
        ///\=.|.|.....|.|.=/
        ///1..|.|.| |.|.|..1
        ////=.|...|!|...|.=\
        ///|....|.\=/.|....|
        ///|.=\.|..E..|./=.|
        ///|..|.../=\...|..|
        ///|=.|.|.\=/.|.|.=|
        ///|o...|..|..|...o|
        ///|.=====.|.=====.|
        ///|3.............4|
        ///\======/2\======/.
        /// </summary>
        internal static string ErraticMap {
            get {
                return ResourceManager.GetString("ErraticMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXXXXXXXXXXXXXXXX
        ///Xo......X......oX
        ///X.XX.XX.X.XX.XX.X
        ///X.XX.XX.X.XX.XX.X
        ///X.XX.........XX.X
        ///X....XXX.XXX....X
        ///XX.X.X.....X.X.XX
        ///1..X.X.X X.X.X..1
        ///XX.X...X!X...X.XX
        ///X....X.XXX.X....X
        ///X.XX.X..E..X.XX.X
        ///X..X...XXX...X..X
        ///XX.X.X.XXX.X.X.XX
        ///X....X..X..X....X
        ///X.XXXXX.X.XXXXX.X
        ///Xo.............oX
        ///XXXXXXXXXXXXXXXXX.
        /// </summary>
        internal static string ExesMap {
            get {
                return ResourceManager.GetString("ExesMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /==================\
        ///o.................o|
        ///. __ .  _______   .|
        ///./  \. / _____ \  .|
        ///.\  /.| /1....\_) .\
        ///. )( .| \___ .......
        ///. || .|  ___) o (_).
        ///. \/ .| /1..........
        ///......| \_____/ ) ./
        ///. () . \_______/  .|
        ///!....E............o|
        ///\==================/.
        /// </summary>
        internal static string IntroScreen {
            get {
                return ResourceManager.GetString("IntroScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                                                                                             
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///                                                      /===============\
        ///                                                      |o......|......o|
        ///                                                      |./\./\.|./\./\.|
        ///                                                      |.||.\/.|.\/.||.|
        ///                                                      |.\/.........\/.|        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LargeMap {
            get {
                return ResourceManager.GetString("LargeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /=====\     /=====\
        ///|E....&apos;=====&apos;....!|
        ///|.&lt;=&gt;.........&lt;=&gt;.|
        ///|.....,==2==,.....|
        ///\=,.,=/     \=,.,=/
        ///  |.|         |.|
        ///  |.1         1.|
        ///  |.|         |.|
        ////=&apos;.&apos;=\     /=&apos;.&apos;=\
        ///|.....|     |.....|
        ///|.,=,.&apos;==2==&apos;.,=,.|
        ///|.&apos;=&apos;.........&apos;=&apos;.|
        ///|!....,=====,....!|
        ///\=====/     \=====/.
        /// </summary>
        internal static string ManyGhostsBasesMap {
            get {
                return ResourceManager.GetString("ManyGhostsBasesMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MEW3 {
            get {
                object obj = ResourceManager.GetObject("MEW3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═╗
        ///║o║
        ///║.║
        ///║.║
        ///║.║
        ///║.║
        ///
        ///
        ///
        ///╚
        ///
        ///╔
        ///
        ///╩
        ///
        ///╦
        ///
        ///╠
        ///
        ///═
        ///
        ///╬
        ///
        ///╣
        ///
        ///║
        ///
        ///╗
        ///
        ///╝.
        /// </summary>
        internal static string Stage1 {
            get {
                return ResourceManager.GetString("Stage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /===============\ 
        /// |o......|......o| 
        /// |./\./\.|./\./\.| 
        /// |.||.\/.|.\/.||.| 
        /// |.\/.........\/.| 
        /// |..../==.==\....| 
        /// \=.|.|.....|.|.=/ 
        ///1...|.|.|!|.|.|...1
        /// /=.|...|!|...|.=\ 
        /// |....|.\=/.|....| 
        /// |.=\.|..E..|./=.| 
        /// |..|.../=\...|..| 
        /// |=.|.|.\=/.|.|.=| 
        /// |....|..|..|....| 
        /// |.=====.|.=====.| 
        /// |o.............o| 
        /// \===============/ .
        /// </summary>
        internal static string TwoGhostsDefaultMap {
            get {
                return ResourceManager.GetString("TwoGhostsDefaultMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /======\2/======\
        ///|4.............3|
        ///|./\./\.|./\./\.|
        ///|.||.\/.|.\/.||.|
        ///|.\/.........\/.|
        ///|o.../==.==\...o|
        ///\=.|.|.....|.|.=/
        ///1..|.|.|!|.|.|..1
        ////=.|...|!|...|.=\
        ///|....|.\=/.|....|
        ///|.=\.|..E..|./=.|
        ///|..|.../=\...|..|
        ///|=.|.|.\=/.|.|.=|
        ///|o...|..|..|...o|
        ///|.=====.|.=====.|
        ///|3.............4|
        ///\======/2\======/.
        /// </summary>
        internal static string TwoGhostsErraticMap {
            get {
                return ResourceManager.GetString("TwoGhostsErraticMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXXXXXXXXXXXXXXXX
        ///Xo......X......oX
        ///X.XX.XX.X.XX.XX.X
        ///X.XX.XX.X.XX.XX.X
        ///X.XX.........XX.X
        ///X....XXX.XXX....X
        ///XX.X.X.....X.X.XX
        ///1..X.X.X!X.X.X..1
        ///XX.X...X!X...X.XX
        ///X....X.XXX.X....X
        ///X.XX.X..E..X.XX.X
        ///X..X...XXX...X..X
        ///XX.X.X.XXX.X.X.XX
        ///X....X..X..X....X
        ///X.XXXXX.X.XXXXX.X
        ///Xo.............oX
        ///XXXXXXXXXXXXXXXXX.
        /// </summary>
        internal static string TwoGhostsExesMap {
            get {
                return ResourceManager.GetString("TwoGhostsExesMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                                                                                             
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///                                                      /===============\
        ///                                                      |o......|......o|
        ///                                                      |./\./\.|./\./\.|
        ///                                                      |.||.\/.|.\/.||.|
        ///                                                      |.\/.........\/.|        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwoGhostsLargeMap {
            get {
                return ResourceManager.GetString("TwoGhostsLargeMap", resourceCulture);
            }
        }
    }
}
