//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazeRunner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MazeRunner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ░░░░░░░░░░░░░░░░░░░░░░░░░░░░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░                          ░
        ///░  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateBorder {
            get {
                return ResourceManager.GetString("CreateBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔════════════╦╦════════════╗
        ///║............║║............║
        ///║.╔══╗.╔═══╗.║║.╔═══╗.╔══╗.║
        ///║o║  ║.║   ║.║║.║   ║.║  ║o║
        ///║.╚══╝.╚═══╝.╚╝.╚═══╝.╚══╝.║
        ///║..........................║
        ///║.╔══╗.╔╗ ╔══════╗ ╔╗.╔══╗.║
        ///║.╚══╝.║║ ╚══╗╔══╝ ║║.╚══╝.║
        ///║......║║    ║║    ║║......║
        ///╚════╗.║╚══╗ ║║ ╔══╝║.╔════╝
        ///     ║.║╔══╝ ╚╝ ╚══╗║.║
        ///     ║.║║          ║║.║
        ///     ║.║║ ╔══  ══╗ ║║.║
        ///═════╝.╚╝ ║      ║ ╚╝.╚═════
        ///1......   ║      ║   ......1
        ///═════╗.╔╗ ║ !!!! ║ ╔╗.╔═════
        ///     ║.║║ ╚══════╝ ║║.║
        ///     ║.║║          ║║. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultIntentMap {
            get {
                return ResourceManager.GetString("DefaultIntentMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                             
        ///                            
        ///                            
        ///                            
        ///                            
        ///                            
        ///                            
        ///                            
        ///                            
        ///                            
        ///                            
        ///                            
        ///                            
        ///                            
        ///                            
        ///                            
        ///                            
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmptyMap {
            get {
                return ResourceManager.GetString("EmptyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔══════════════════════════╗
        ///║                          ║
        ///║ o . . . . . E. . . . . o ║
        ///║                          ║
        ///║ .                      . ║
        ///║                          ║
        ///║ .                      . ║
        ///║                          ║
        ///║ .                      . ║
        ///║                          ║
        ///║ .                      . ║
        ///║          ╔═════╗         ║
        ///║ .        ║ ╔═╗ ║       . ║
        ///║          ║ ║!║ ║         ║
        ///║ .        ║ ║!║ ║       . ║
        ///║ o        ║ ║ ║ ║       o ║
        ///║ .        ╚═╝ ╚═╝       . ║
        ///║  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IntroScreen {
            get {
                return ResourceManager.GetString("IntroScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MEW3 {
            get {
                object obj = ResourceManager.GetObject("MEW3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔════════════╗╔════════════╗
        ///║............║║............║
        ///║.╔══╗.╔═══╗.║║.╔═══╗.╔══╗.║
        ///║.║  ║.║   ║.║║.║   ║.║  ║.║
        ///║.╚══╝.╚═══╝.╚╝.╚═══╝.╚══╝.║
        ///║..........................║
        ///║.╔══╗.╔╗ ╔══════╗ ╔╗.╔══╗.║
        ///║.╚══╝.║║ ╚══╗╔══╝ ║║.╚══╝.║
        ///║......║║    ║║    ║║......║
        ///╚════╗.║╚══╗ ║║ ╔══╝║.╔════╝
        ///     ║.║╔══╝ ╚╝ ╚══╗║.║
        ///     ║.║║          ║║.║
        ///     ║.║║ ╔══  ══╗ ║║.║
        ///╔════╝.╚╝ ║      ║ ╚╝.╚════╗
        ///║1.....   ║      ║   .....1║
        ///╚════╗.╔╗ ║ !!!! ║ ╔╗.╔════╝
        ///     ║.║║ ╚══════╝ ║║.║
        ///     ║.║║          ║║. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OutroScreen {
            get {
                return ResourceManager.GetString("OutroScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔══════════════════════════╗
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║                          ║
        ///║  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScreenBorder {
            get {
                return ResourceManager.GetString("ScreenBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔════════════╗╔════════════╗
        ///║............║║............║
        ///║.╔══╗.╔═══╗.║║.╔═══╗.╔══╗.║
        ///║o║  ║.║   ║.║║.║   ║.║  ║o║
        ///║.╚══╝.╚═══╝.╚╝.╚═══╝.╚══╝.║
        ///║..........................║
        ///║.╔══╗.╔╗ ╔══════╗ ╔╗.╔══╗.║
        ///║.╚══╝.║║ ╚══╗╔══╝ ║║.╚══╝.║
        ///║......║║    ║║    ║║......║
        ///╚════╗.║╚══╗ ║║ ╔══╝║.╔════╝
        ///     ║.║╔══╝ ╚╝ ╚══╗║.║
        ///     ║.║║          ║║.║
        ///     ║.║║ ╔══  ══╗ ║║.║
        ///╔════╝.╚╝ ║      ║ ╚╝.╚════╗
        ///║1.....   ║      ║   .....1║
        ///╚════╗.╔╗ ║  !!  ║ ╔╗.╔════╝
        ///     ║.║║ ╚══════╝ ║║.║
        ///     ║.║║          ║║. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stage1 {
            get {
                return ResourceManager.GetString("Stage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔══════════════════════════╗
        ///║........    E     ........║
        ///║o╔════╗.╔═╗ ╔╗ ╔═╗.╔════╗o║
        ///║.║    ║.║ ║ ║║ ║ ║.║    ║.║
        ///║.║    ║.║ ║ ║║ ║ ║.║    ║.║
        ///║.║    ║.║ ║ ║║ ║ ║.║    ║.║
        ///║.║    ║.║ ║ ║║ ║ ║.║    ║.║
        ///║.║    ║.╚═╝ ╚╝ ╚═╝.║    ║.║
        ///║.║    ║............║    ║.║
        ///║1║    ╚════════════╝    ║2║
        ///╚═╝                      ╚═╝
        ///╔═╗                      ╔═╗
        ///║1║╔════════════════════╗║2║
        ///║.║║....................║║.║
        ///║.║║.╔═╗.╔══╗  ╔══╗.╔═╗.║║.║
        ///║.║║.║ ║.║  ║  ║  ║.║ ║.║║.║
        ///║.║║.║ ║.║  ║  ║  ║.║ ║.║║.║
        ///║. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stage2 {
            get {
                return ResourceManager.GetString("Stage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔════════════╗╔════════════╗
        ///║............║║............║
        ///║.╔════════╗.║║.╔════════╗.║
        ///║.║........║.║║.║........║.║
        ///║.║.╔════╗.║.║║.║.╔════╗.║.║
        ///║.║.║....║.║.║║.║.║....║.║.║
        ///║.║.║.╔╗.║.║.║║.║.║.╔╗.║.║.║
        ///║.║.║.║║.║.║.║║.║.║.║║.║.║.║
        ///║.║.║.╚╣.║.║.║║.║.║.╠╝.║.║.║
        ///║.║.║.1║.║.║.║║.║.║.║1.║.║.║
        ///║.║.╚══╝.║.║.║║.║.║.╚══╝.║.║
        ///║.║......║.║.║║.║.║......║.║
        ///║.╚══════╝.║.║║.║.╚══════╝.║
        ///║..........║E║║3║..........║
        ///║ ╔════════╩═╝╚═╩════════╗ ║
        ///║ ║                      ║ ║
        ///║ ╚════════╦═╗╔═╦════════╝ ║
        ///║. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stage3 {
            get {
                return ResourceManager.GetString("Stage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                             
        ///                            
        ///                            
        ///                            
        ///   ╔═══════╗    ╔═══════╗   
        ///   ║4......║    ║......4║   
        ///   ║.╔╗ ╔╗.║    ║.╔╗ ╔╗.║   
        ///   ║.╚╝ ╚╝.║    ║.╚╝ ╚╝.║   
        ///   ║.     .║    ║.     .║   
        ///   ║.╔╗ ╔╗.║    ║.╔╗ ╔╗.║   
        ///   ║.╚╝ ╚╝.║    ║.╚╝ ╚╝.║   
        ///   ║......5║    ║3......║   
        ///   ╚═══════╝    ╚═══════╝   
        ///                            
        ///╔════════════╗╔════════════╗
        ///║E          1║║5.........!o║
        ///╚════════════╝╚════════════╝
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stage4 {
            get {
                return ResourceManager.GetString("Stage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                             
        ///                            
        /// ╔════╦══════════════╦════╗ 
        /// ║3...║              ║...3║ 
        /// ║ ╔╗.║              ║.╔╗ ║ 
        /// ║ ╚╝.║              ║.╚╝ ║ 
        /// ║o  4║              ║2  o║ 
        /// ╠════╝              ╚════╣ 
        /// ║     ╔════╗  ╔════╗     ║ 
        /// ║     ║4  o║  ║o  2║     ║ 
        /// ║     ║.╔╗ ║  ║ ╔╗.║     ║ 
        /// ║     ║.╚╝ ║  ║ ╚╝.║     ║ 
        /// ║     ║...5║  ║1...║     ║ 
        /// ║     ╚════╬══╬════╝     ║ 
        /// ║E        1║  ║5        !║ 
        /// ║         6║  ║0        !║ 
        /// ║     ╔════╬══╬════╗     ║ 
        /// ║ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stage5 {
            get {
                return ResourceManager.GetString("Stage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════╗╔════════════╗╔═════╗
        ///║!   1║║1 ........ 2║║2   !║
        ///╚═════╝╚═╗.╔════╗.╔═╝╚═════╝
        ///         ║.║    ║.║         
        ///         ║.║    ║.║         
        ///         ║.║    ║.║         
        ///╔═════╗╔═╝.╚════╝.╚═╗╔═════╗
        ///║!   3║║3 ........ 4║║4   !║
        ///╚═════╝╚═╗.╔════╗.╔═╝╚═════╝
        ///         ║.║    ║.║         
        ///         ║.║    ║.║         
        ///         ║.║    ║.║         
        ///╔════════╝.╚════╝.╚════════╗
        ///║..........................║
        ///║.╔═╗ ╔ ╗   ╔ ═╗   ╔ ╗ ╔═╗.║
        ///║.║o║ ║o║   ║oo║   ║o║ ║o║.║
        ///║.╚ ╝ ╚═╝   ╚═ ╝   ╚═╝ ╚ ╝.║
        ///║. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stage6 {
            get {
                return ResourceManager.GetString("Stage6", resourceCulture);
            }
        }
    }
}
